spring:
  datasource:
    url: jdbc:postgresql://auth-db:5432/authdb
    username: authuser
    password: authpass
  data:
    redis:
      host: redis
      port: 6379

user:
  service:
    url: http://user-service:8082

server:
  port: 8081