services:
  auth-service:
    base-url: http://auth-service:8081
  user-service:
    base-url: http://user-service:8082
  order-service:
    base-url: http://order-service:8083
  payment-service:
    base-url: http://payment-service:8084

spring:
  data:
    redis:
      host: redis
