spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/testdb
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 200ms

  cache:
    type: none

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true

logging:
  level:
    com.ausiankou: DEBUG
    org.springframework.jdbc: DEBUG
    org.hibernate.SQL: DEBUG