apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices
type: Opaque
stringData:
  JWT_SECRET: "prod-please-change-this-secret-min-32-bytes-long-random-value"
  AUTH_DB_USER: auth_user
  AUTH_DB_PASSWORD: auth_pass
  USER_DB_USER: user_user
  USER_DB_PASSWORD: user_pass
  ORDER_DB_USER: order_user
  ORDER_DB_PASSWORD: order_pass
  PAYMENT_DB_USER: payment_user
  PAYMENT_DB_PASSWORD: payment_pass
