spring:
  data:
    mongodb:
      uri: mongodb://${PAYMENT_DB_USER:payment_user}:${PAYMENT_DB_PASSWORD:payment_pass}@payment-db:27017/${PAYMENT_DB_NAME:payment_db}?authSource=admin&replicaSet=rs0
  kafka:
    bootstrap-servers: kafka:9092
